nodejs/import-in-the-middle

lib/register.js, test/hook/define-property.js, test/hook/dynamic-import.js, test/hook/dynamic-import.mjs, test/hook/static-import.mjs, test/low-level/dynamic-import.js, test/low-level/static-import.mjs
This PR adds support for calling `defineProperty` on exports to allow using `shimmer` and similar implementations. It also fixes the tests that were checking if the module name contains `os` instead of checking it's exactly `os`.
=> add support for calling defineProperty on exports

hook.mjs, package.json, test/other/executable, test/other/import-executable.mjs
Roughly replicates the behaviour of stock Node.js without loaders where
extensionless entrypoints are treated as CJS.
This allows IITM to work with such tools as mocha.
=> support extensionless entrypoints

.github/workflows/ci.yml, hook.mjs
In Node.js 17.6.0, arbitrary protocol names can't be passed through the
hooks. Here we bypass this check by changing the prefix used.
Before:
iitm:
After:
file:iitm:
This way it looks like a file URL.
=> fix for Node.js 17.6.0

.github/workflows/ci.yml, hook.mjs
`file:node:something` was a invalid url and the last node v16.17.0 version throws an error if the URL is not valid.
=> Fix hook in node 16.17.0

.github/workflows/ci.yml, index.js, package.json, test/hook/static-import-package-internals-enabled.mjs, test/runtest, test/runtest.bat
This PR fixes the bug that occurs in Windows where non-internal module loading is not intercepted due to the platform-specific path segment separator.
=> Fix module interception on windows

.github/workflows/ci.yml, test/other/import-executable.mjs
Node.js 18.19 backported the extensionless supported added ion Node.js 21.0.0 and 20.10.0, so the test needed to be fixed for that.
=> Extensionless support in 18.19

hook.js, test/get-esm-exports/v18.19-get-esm-exports.js, test/runtest
Node v18.19.0 includes a backport of ESM loading on a separate thread -- https://github.com/nodejs/node/commit/bac9b1758f36fb3504589ffc5ed610d574dca47d. This PR updates the version check to use AST parsing on Node >= 18.19.0.
=> Fix ESM in Node v18.19.0

hook.js, lib/get-esm-exports.js, package.json, test/fixtures/a.mjs, test/fixtures/b.mjs, test/fixtures/bundle.mjs, test/fixtures/esm-exports.txt, test/fixtures/fantasia.mjs, test/fixtures/foo.mjs, test/fixtures/lib/baz.mjs, test/hook/static-import-star.mjs
This change adds support for modules that export entities through the `export * from 'module'` ESM syntax. This resolves issue #31.
=> Support `export * from 'module'` ESM syntax

.github/workflows/ci.yml, package.json
=> Combine coverage across all builds

hook.js, test/hook/module-toStringTag.mjs
The README example says the Hook callback `exported` arg is
"effectively `import * as exported from ${url}`".
https://tc39.es/ecma262/#sec-module-namespace-objects specs that
a Module Namespace Object has a `@@toStringTag` property with value
"Module" and no constructor.
Fixes: #57
Obsoletes: #64
* * *
This behaviour changed with the changes in #43 when the `register(...)`'d namespace changed from using an actual imported module object to using a plain object with module properties copied over to it:
https://github.com/DataDog/import-in-the-middle/pull/43/files#diff-e69a24a4c3746fa1ee96a78e12bb12d2dd4eb6e4cacbced2bf1f4084952681d9L130-R208
I suspect that was an unintentional change.
The main question here is **whether you would like import-in-the-middle to promise this**: that the …
=> fix: ensure the hooked module exports has @@toStringTag property

lib/get-esm-exports.js, package.json
This dependency appears to have been renamed since 1.9.0: observe that github.com/xtuc/acorn-import-assertions redirects to https://github.com/xtuc/acorn-import-attributes.
In 1.9.2 a security vulnerability was addressed (fully qualifying a package reference to prevent a confusion attack), which is being introduced into our codebase via this repo (by way of `dd-trace`).
Validated that all current tests still pass with this update.
=> Use updated/renamed version of acorn-import-assertions (security fix)

.npmrc
Would you consider a .npmrc file to not create a package-lock file?
The reason I'm suggesting it, is because I had a short bit of confusion in one of my working copies when tests were failing on the tip of "main" -- even after a `rm -rf node_modules && npm install`. My package-lock.json, which I neglected to also delete, happened to be locking some dep such that some tests failed. I didn't check at the time what deps caused it.
Totally fine if you don't want this file.
=> chore: don't create a package-lock file

index.d.ts, test/typescript/ts-node.test.mts
In #88 I added a named `Hook` export but forgot to update the TypeScript types!
=> fix: Named export `Hook` missing from types

hook.js
=> fix: `parentResolve` is not a function

lib/get-esm-exports.js, lib/get-exports.js, test/fixtures/node_modules/some-external-cjs-module/index.js, test/fixtures/node_modules/some-external-cjs-module/package.json, test/fixtures/re-export-cjs-built-in.js, test/fixtures/re-export-cjs.js, test/get-esm-exports/v20-get-esm-exports.js, test/hook/re-export-cjs.mjs
Closes #95
I've also made the `getExports` functions return `Set<string>` instead of `string[]` as this saves a load of unnecessary allocations. 
I've also run this through the additional module tests in #93 and get the same results.
=> fix: CommonJs bare specifier resolution

hook.js, test/fixtures/duplicate-b.mjs, test/fixtures/duplicate-c.mjs, test/fixtures/duplicate-explicit.mjs, test/hook/duplicate-exports-explicit.mjs, test/hook/duplicate-exports.mjs, test/hook/v18.19-openai.mjs
=> fix: Explicitly named exports should be exported over `export *`

hook.js
Uses `process.emitWarning` rather than `console.warn` to log error messages when failing to wrap a module.
This means that by default the warnings are truncated. You can get full stack traces by passing `--trace-warnings` and you can hide the warnings with `--no-warnings`.
=> fix: Use `process.emitWarning` to log errors

lib/get-exports.js
Since #106 might not get merged, I cherry picked the improvements to logged error messages when module wrapping fails due to parsing failures.
`processModule` may parse multiple files in the process of wrapping a module so it's important to log the exact file the fails parsing.
```
Error: 'import-in-the-middle' failed to wrap 'file:///Users/tim/Documents/Repositories/import-in-the-middle/test/fixtures/json-attributes.mjs'
at load (/Users/tim/Documents/Repositories/import-in-the-middle/hook.js:306:21)
at async nextLoad (node:internal/modules/esm/hooks:750:22)
at async Hooks.load (node:internal/modules/esm/hooks:383:20)
at async MessagePort.handleMessage (node:internal/modules/esm/worker:199:18) {
cause: Error: Failed to parse 'file:///Users/tim/Documents/Repositories/import-in-the-middle/te …
```
=> fix: Include source url for parsing failures

lib/get-exports.js, test/fixtures/index.js, test/fixtures/require-root.js, test/hook/require-root-cjs.mjs
Closes #116 and closes #97
While trying to create a minimal reproduction for #106, I found that the issue was caused by the following CommonJs in `@prisma/client`:
```ts
module.exports = { ...require('.') }
```
`require('.')` was getting resolved to `{cwd}/index.js` whereas it should be resolving to `./`, ie. the index file in the same directory as the current file `./index.js`.
=> fix: CJS `require('.')` resolution

LICENSE, NOTICE
- Closes #121
As per the [Apache 2.0 docs](https://www.apache.org/legal/apply-license.html#new), `LICENSE` should contain the actual Apache 2.0 license text so I added that.
The text that used to be in `LICENSE` has now moved to `NOTICE` and has been updated to include `Copyright 2024 Node.js contributors` while retaining the previous DataDog copyright.
=> chore: Update `LICENSE` and `NOTICE`

CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md
Closes #122
- `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` come from other Node repos
- `GOVERNANCE.md` was copied from the Nodejs repo with lots of irrelevent detail removed and PR approvals modified.
=> chore: Add `CODE_OF_CONDUCT`, `GOVERNANCE` and update `CONTRIBUTING`

.github/workflows/release-please.yml, release-please-config.json
So the docs don't specifcally mention this but I found an [issue that mentions a solution](https://github.com/googleapis/release-please-action/issues/941#issuecomment-2036412965). If you inlcude any actions parameters other than `token`, `config-file`, or `manifest-file`, the config file will not be read correctly. 
That's a couple of hours of my life I'll never get back!
=> chore: More `release-please` fixes

.github/workflows/release-please.yml, release-please-config.json
I'll replace this token with @nodejs-github-bot's one ASAP. At the moment it is my token with 30 days expiration.
Also adds a `bootstrap-sha` to exclude commits before 1.8.1: https://github.com/nodejs/import-in-the-middle/pull/135#issuecomment-2213936224
=> chore: add release-please github token

hook.js, package.json, test/hook/vue-server-renderer.mjs
Closes #139
When we resolve sub-modules to get their exports, `parentResolve` can return a different `format` to the current module type and this should be used when loading the module source!
This change is potnetially a one-liner but I refactored the code a bit to avoid initially setting `let` variables as undefined only to set them later in an if/else.
=> fix: Use correct `format` when resolving exports from sub-modules

hook.js, test/hook/vue-server-renderer.mjs
Closes #144
So I fixed the transition from ESM to CJS when loading sub-modules for export evaluation via a bare specifier in #140... but unsurprisingly this is also required when resolving realtive paths too.
As @jsumners-nr once said:
> we seem to be playing whack-a-mole with the ludicrous number of permutations
=> fix: Use correct `format` when resolving exports from relative paths

README.md, hook.js, test/register/v18.19-exclude-regex.mjs
This PR allows you to pass regular expressions in the `include` and `exclude` options.
cc @FabianFrank and @vchirikov
=> feat: Allow regex for `include` and `exclude` options

hook.js, test/register/v18.19-include-builtin.mjs
@trentm found a bug in `node:` prefixed built-in modules when using `include` and `exclude`:
https://github.com/nodejs/import-in-the-middle/pull/146#issuecomment-2253093908
This PR fixes that bug and adds some tests for it.
=> fix: `node:` prefixed build-in modules with `include`/`exclude`

hook.js, test/fixtures/import-absolute-after.mjs, test/fixtures/import-absolute.mjs, test/register/v18.19-include-message-port-absolute-path.mjs
`@opentelemetry/instrumentation-aws-lambda` hooks an absolute path but this was not supported by the `include` option. Previously it would have only worked if you passed a file URL when registering the hook.
=> feat: Support absolute paths for `include`

test/fixtures/native-modules/aix-ppc64.js, test/fixtures/native-modules/linux-ppc64.js, test/fixtures/native-modules/linux-s390x.js
Skip `test/hook/v14-native-modules.mjs` when no native module is available for the platform.
---
The `@node-rs/crc32-*` module that the test uses [isn't available](https://github.com/napi-rs/node-rs/blob/37e3e833972bde738b055ebaa1ad01a3e4ee2c98/packages/crc32/package.json#L28-L41) on all os-arch combinations.
First noticed in citgm runs, e.g. https://ci.nodejs.org/job/citgm-smoker/nodes=rhel8-s390x/3520/testReport/junit/(root)/citgm/import_in_the_middle_v1_11_3/
```console
not ok 30 test/hook/v14-native-modules.mjs
---
stdout: ''
stderr: >-
node:internal/modules/run_main:104
triggerUncaughtException(
^
Error: Cannot find module
'/home/iojs/tmp/citgm_tmp/7285591d-3030-4e14-904d-0a9c0040c0a7/import-in-the-middle/test/fixtures/native-modules/linux-s390x.js'
imported from …
```
=> test: skip test when native module is not available

lib/get-esm-exports.js, package.json, test/hook/v20.10-static-import-attributes.mjs
Bumps the `acorn` version to the latest which now supports import attributes
=> feat: Support import attributes 

hook.js, test/fixtures/circular-a.mjs, test/fixtures/circular-b.mjs, test/register/v18.19-circular.mjs
Fixes #163
In the integration CI, this fixes importing the svelte package.
It does not result in identical behavior to Node.js, but this is very much a corner case:
```javascript
// Importing 'a' first will fail in Node.js (with or without the loader)
await import('./test/fixtures/circular-a.mjs')
await import('./test/fixtures/circular-b.mjs')
```
```javascript
// If you try and ignore the error
try { await import('./test/fixtures/circular-a.mjs') } catch { }
// it affects the subsequent import of 'b', which will now fail
await import('./test/fixtures/circular-b.mjs')
```
```javascript
// If 'b' is imported first, it succeeds (as in the test case)
await import('./test/fixtures/circular-b.mjs')
// If the import of 'a' is done after, it also succeeds with { foo: 1, bar: 2 }
// With this PR, …
```
=> fix: handling of circular dependencies

hook.js
A warning is printed when using context.importAssertions instead of context.importAttributes since Node.js v21.0.0, v20.10.0 and v18.19.0.
Fixes #172
=> fix: warning from use of context.importAssertions

package.json
`openai` has lots of churn and it takes quite a lot of effort to keep our CI passing.
This PR pins the version so we are still testing the behaviour it was originally added as a dependency for. We are no longer tested any breaking changes it might introduce.
=> test: Pin openai version

README.md, hook.js, index.js, lib/register.js, test/register/v18.19-experimental-patch-internals.mjs
As discussed in the Diagnostics Working Group meeting, this PR is similar to #189 but allows this change to be selectively enabled so it can be tested more thoroughly before becoming the default.
Sentry are happy to do this testing!
=> feat: Optionally hook internal paths like `require-in-the-middle`

.github/workflows/release-please.yml
OIDC support is only available in npm >=11.5.1
Refs: https://github.com/nodejs/import-in-the-middle/pull/203
Refs: https://github.com/nodejs/admin/issues/998
=> chore: use npm@11 for OIDC publishing
